# Generated by Django 5.0.6 on 2024-05-21 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forumai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phenylalanine', models.DecimalField(decimal_places=2, max_digits=6)),
                ('measure', models.CharField(max_length=255)),
                ('homePhenylalanine', models.DecimalField(decimal_places=2, max_digits=6)),
                ('homeWeight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receptai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalorijos', models.FloatField(default=0.0)),
                ('pavadinimas', models.CharField(max_length=255)),
                ('fenilalaninas', models.FloatField(default=0.0)),
                ('baltymai', models.FloatField(default=0.0)),
                ('aprasas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Irasai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstas', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('fk_Forumasid_Forumas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.forumai')),
            ],
        ),
        migrations.CreateModel(
            name='Naudotojai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=255)),
                ('lolname', models.CharField(max_length=255, null=True)),
                ('tier', models.CharField(max_length=255, null=True)),
                ('rank', models.CharField(max_length=255, null=True)),
                ('puuid', models.CharField(max_length=255, null=True)),
                ('pavarde', models.CharField(max_length=255)),
                ('telefonas', models.CharField(max_length=255)),
                ('el_pastas', models.CharField(max_length=255)),
                ('gimimo_data', models.DateField()),
                ('level', models.IntegerField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kraujo_tyrimai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('fenilalaninas', models.IntegerField()),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
            ],
        ),
        migrations.CreateModel(
            name='Komentarai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstas', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('fk_Irasasid_Irasas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.irasai')),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to='homepage.naudotojai')),
            ],
        ),
        migrations.AddField(
            model_name='irasai',
            name='fk_Naudotojasid_Naudotojas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai'),
        ),
        migrations.CreateModel(
            name='Naudotojo_receptai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
                ('fk_Receptasid_Receptas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.receptai')),
            ],
        ),
        migrations.CreateModel(
            name='Megstamiausi_receptai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
                ('fk_Receptasid_Receptas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.receptai')),
            ],
        ),
        migrations.CreateModel(
            name='Recepto_produktai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fk_Produktasid_Produktas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
                ('fk_Receptasid_Receptas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.receptai')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
                ('members', models.ManyToManyField(related_name='teams_joined', to='homepage.naudotojai')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rankRequirement', models.CharField(max_length=255, null=True)),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
                ('registered_users', models.ManyToManyField(related_name='registered_tournaments', to='homepage.naudotojai')),
            ],
        ),
        migrations.CreateModel(
            name='Valgiarasciai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diena', models.IntegerField()),
                ('bendras_fenilalaninas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bendras_baltymas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('data', models.DateField()),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
            ],
        ),
        migrations.CreateModel(
            name='Valgymai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipas', models.CharField(max_length=255)),
                ('bendras_baltymas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('bendras_fenilalaninas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fk_Valgiarastisid_Valgiarastis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.valgiarasciai')),
            ],
        ),
        migrations.CreateModel(
            name='Valgomas_produktas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fk_Produktasid_Produktas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
                ('fk_Valgymasid_Valgymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.valgymai')),
            ],
        ),
        migrations.CreateModel(
            name='Valgymo_receptas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fk_Receptasid_Receptas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.receptai')),
                ('fk_Valgymasid_Valgymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.valgymai')),
            ],
        ),
    ]
