# Generated by Django 5.0.6 on 2024-05-26 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
                ('users', models.ManyToManyField(related_name='registered_in_team', to='homepage.naudotojai')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='registered_teams',
            field=models.ManyToManyField(related_name='registered_teams', to='homepage.tournamentteam'),
        ),
    ]
