# Generated by Django 5.0.2 on 2024-05-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_opa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opa',
        ),
    ]
