# Generated by Django 5.0.6 on 2024-05-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_tournamentteam_tournament_registered_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registered_teams',
            field=models.ManyToManyField(related_name='registered_tournaments_teams', to='homepage.tournamentteam'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registered_users',
            field=models.ManyToManyField(related_name='registered_tournaments_solo', to='homepage.naudotojai'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='users',
            field=models.ManyToManyField(related_name='registered_in_tournament_team', to='homepage.naudotojai'),
        ),
    ]
