# Generated by Django 5.0.2 on 2024-05-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_delete_opa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='fk_Naudotojasid_Naudotojas',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='rankRequirement',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='registered_users',
        ),
    ]
