# Generated by Django 5.0.6 on 2024-05-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_tournament_registered_teams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=1000)),
                ('action_taken', models.BooleanField(default=False)),
                ('action_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='homepage.naudotojai')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_reports', to='homepage.naudotojai')),
            ],
        ),
    ]
