# Generated by Django 5.0.6 on 2024-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=30),
        ),
    ]
