# Generated by Django 5.0.2 on 2024-05-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_tournament_fk_naudotojasid_naudotojas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fk_Naudotojasid_Naudotojas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rankRequirement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registered_users',
            field=models.ManyToManyField(related_name='registered_tournaments', to='homepage.naudotojai'),
        ),
    ]
