# Generated by Django 5.0.2 on 2024-05-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_tournament_fk_naudotojasid_naudotojas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naudotojai',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
    ]
