# Generated by Django 5.0.6 on 2024-05-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_tournament_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=30),
        ),
    ]
