# Generated by Django 5.0.2 on 2024-05-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_naudotojai_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naudotojai',
            old_name='el_pastas',
            new_name='email',
        ),
    ]
