# Generated by Django 5.0.2 on 2024-04-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_remove_komentarai_likes_komentarai_likes'),
        ('homepage', '0017_merge_20240418_1842'),
    ]

    operations = [
    ]
