# Generated by Django 5.0.2 on 2024-04-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_komanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='komanda',
            name='fk_Naudotojasid_Naudotojas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai'),
            preserve_default=False,
        ),
    ]
