# Generated by Django 5.0.2 on 2024-04-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_komanda_fk_naudotojasid_naudotojas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Komanda',
            new_name='Team',
        ),
    ]
