# Generated by Django 5.0.6 on 2024-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_rename_komanda_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naudotojai',
            name='accountid',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='lolname',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='puuid',
        ),
        migrations.AddField(
            model_name='receptai',
            name='baltymai',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='valgiarasciai',
            name='bendras_baltymas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='valgymai',
            name='bendras_baltymas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='valgymai',
            name='bendras_fenilalaninas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='valgiarasciai',
            name='bendras_fenilalaninas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Mėgstamiausi_receptai',
        ),
    ]
