# Generated by Django 5.0.2 on 2024-05-20 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rankRequirement', models.CharField(max_length=255)),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
            ],
        ),
    ]
