# Generated by Django 5.0.6 on 2024-05-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_remove_naudotojai_accountid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naudotojai',
            name='lolname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='naudotojai',
            name='puuid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
