# Generated by Django 5.0.6 on 2024-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_naudotojai_lolname_naudotojai_puuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naudotojai',
            name='rank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='naudotojai',
            name='tier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
