# Generated by Django 5.0.2 on 2024-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registered_users',
            field=models.ManyToManyField(related_name='registered_tournaments', to='homepage.naudotojai'),
        ),
    ]
